name: Docs

env:
  USE_LOCKFILE: ${{ secrets.USE_LOCKFILE }}
  ENABLE_DOCS: ${{ secrets.ENABLE_DOCS }}

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ docs ]

jobs:
  docs:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["latest"]

    steps:

    # region Setup
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest

    - uses: actions/setup-node@v4
      name: Setting Up Node.js (${{ matrix.node-version }})
      with:
        node-version: ${{ matrix.node-version }}
        cache: ${{ env.USE_LOCKFILE == 'true' && 'pnpm' || '' }}

    - run: pnpm install --frozen-lockfile
      if: "env.USE_LOCKFILE == 'true'"

    - run: pnpm install --no-lockfile
      if: "env.USE_LOCKFILE != 'true'"
    # regionend

    # region Steps
    - run: pnpm build

    - run: pnpm lint

    - run: pnpm doc

    # for storybook tests
    - run: pnpx playwright install --with-deps

    # this builds storybook into docs/storybook
    - run: pnpm test

    - name: Documentation
      if: "env.ENABLE_DOCS == 'true'"
      uses: crazy-max/ghaction-github-pages@v4
      with:
        jekyll: false
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "env.ENABLE_DOCS is ${{ env.ENABLE_DOCS }}, no documentation can be published" && exit 1
      if: "env.ENABLE_DOCS != 'true'"
    # regionend
